### ISSUE TITLE
Mention experimental ARM emulation in the project description

### ISSUE THREAD

**Issue by jevinskie** [pydrofoil/pydrofoil#90]
Very cool project! I’ve been playing around with Sail and unrelatedly with Graal/Truffle and PyPy/RPython. I didn’t realize until I read @cfbolz’s issue in sail-arm and then read the Pydrofoil dev docs that ARM is experimentally supported. I would have taken a much closer look at this project earlier if that was mentioned in the description/README. =)

**Comment by cfbolz** [comment]
@jevinskie thanks a lot! yeah, I'm totally behind in talking about and publicizing the ARM part of the project, didn't even write a blog post yet :-(.

Anything in particular you'd be interested in doing with Pydrofoil? I'm super happy to hear about ideas for applications because so far this has been a bit of an academic exercise (fun though!). Happy to chat about it too, if that would be helpful.
